"""Install / remove the daily schedule: launchd (macOS) or a systemd user timer.

Both wrap the run in a sleep inhibitor (caffeinate / systemd-inhibit): an
early-morning slot usually fires during a brief wake, and without it the
machine re-sleeps mid-run and TLS handshakes time out. Hourly retry slots
cover a slot that still misses; the stamp file keeps delivery to once/day.
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

from . import config

LABEL = "local.ft-to-kindle"
PLIST = Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"
SYSTEMD_DIR = Path.home() / ".config" / "systemd" / "user"
SERVICE = SYSTEMD_DIR / "ft-to-kindle.service"
TIMER = SYSTEMD_DIR / "ft-to-kindle.timer"


def ft2k_command() -> list[str]:
    """Absolute command that runs `ft2k run` from a bare scheduler env."""
    exe = shutil.which("ft2k")
    if exe and Path(exe).resolve().parent == Path(sys.executable).resolve().parent:
        return [exe, "run"]
    return [sys.executable, "-m", "ft2k", "run"]


def _sh(cmd: list[str], check=True, **kw) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=check, text=True, capture_output=True, **kw)


# --- macOS ------------------------------------------------------------------

def _plist_text() -> str:
    args = ["/usr/bin/caffeinate", "-is", *ft2k_command()]
    arg_xml = "\n".join(f"        <string>{a}</string>" for a in args)
    slots = "\n".join(
        f"        <dict><key>Hour</key><integer>{h}</integer><key>Minute</key><integer>0</integer></dict>"
        for h in config.SCHEDULE_HOURS)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{LABEL}</string>
    <!-- Generated by `ft2k install`; re-run it after upgrading ft2k. -->
    <key>ProgramArguments</key>
    <array>
{arg_xml}
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
        <key>HOME</key>
        <string>{Path.home()}</string>
    </dict>
    <key>StartCalendarInterval</key>
    <array>
{slots}
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>{config.LOG_FILE}</string>
    <key>StandardErrorPath</key>
    <string>{config.LOG_FILE}</string>
</dict>
</plist>
"""


def _uid() -> int:
    return os.getuid()


def install_launchd() -> str:
    PLIST.parent.mkdir(parents=True, exist_ok=True)
    config.LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    if PLIST.exists():
        _sh(["launchctl", "bootout", f"gui/{_uid()}/{LABEL}"], check=False)
    PLIST.write_text(_plist_text())
    _sh(["launchctl", "bootstrap", f"gui/{_uid()}", str(PLIST)])
    return f"launchd agent {LABEL} installed ({PLIST})"


def uninstall_launchd() -> str:
    _sh(["launchctl", "bootout", f"gui/{_uid()}/{LABEL}"], check=False)
    if PLIST.exists():
        PLIST.unlink()
    return f"launchd agent {LABEL} removed"


def status_launchd() -> str:
    r = _sh(["launchctl", "print", f"gui/{_uid()}/{LABEL}"], check=False)
    if r.returncode != 0:
        return "not installed"
    state = next((l.strip() for l in r.stdout.splitlines() if "state =" in l), "loaded")
    return f"installed - {state}; slots {config.SCHEDULE_HOURS[0]:02d}:00-{config.SCHEDULE_HOURS[-1]:02d}:00"


def kick_launchd() -> None:
    _sh(["launchctl", "kickstart", f"gui/{_uid()}/{LABEL}"])


# --- Linux ------------------------------------------------------------------

def _service_text() -> str:
    inhibit = shutil.which("systemd-inhibit") or "/usr/bin/systemd-inhibit"
    cmd = " ".join(f'"{a}"' for a in ft2k_command())
    return f"""# Generated by `ft2k install`; re-run it after upgrading ft2k.
[Unit]
Description=Deliver today's myFT edition to the Kindle

[Service]
Type=oneshot
ExecStart={inhibit} --what=sleep:idle --mode=block --who=ft-to-kindle --why="Fetching myFT" {cmd}
StandardOutput=append:{config.LOG_FILE}
StandardError=append:{config.LOG_FILE}
TimeoutStartSec=45min
"""


def _timer_text() -> str:
    h0, h1 = config.SCHEDULE_HOURS[0], config.SCHEDULE_HOURS[-1]
    return f"""# Generated by `ft2k install`.
[Unit]
Description=Daily myFT to Kindle ({h0:02d}:00, hourly retries until {h1:02d}:00)

[Timer]
OnCalendar=*-*-* {h0:02d}..{h1:02d}:00:00
Persistent=true

[Install]
WantedBy=timers.target
"""


def install_systemd() -> str:
    SYSTEMD_DIR.mkdir(parents=True, exist_ok=True)
    config.LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    SERVICE.write_text(_service_text())
    TIMER.write_text(_timer_text())
    _sh(["systemctl", "--user", "daemon-reload"])
    _sh(["systemctl", "--user", "enable", "--now", "ft-to-kindle.timer"])
    linger = _sh(["loginctl", "enable-linger", os.environ.get("USER", "")], check=False)
    note = "" if linger.returncode == 0 else " (could not enable linger; the timer only runs while you're logged in)"
    return f"systemd user timer installed ({TIMER}){note}"


def uninstall_systemd() -> str:
    _sh(["systemctl", "--user", "disable", "--now", "ft-to-kindle.timer"], check=False)
    for p in (SERVICE, TIMER):
        if p.exists():
            p.unlink()
    _sh(["systemctl", "--user", "daemon-reload"], check=False)
    return "systemd user timer removed"


def status_systemd() -> str:
    r = _sh(["systemctl", "--user", "list-timers", "ft-to-kindle.timer", "--no-pager", "--no-legend"], check=False)
    line = r.stdout.strip()
    if r.returncode != 0 or not line or not TIMER.exists():
        return "not installed"
    return f"installed - next: {' '.join(line.split()[:4])}"


def kick_systemd() -> None:
    _sh(["systemctl", "--user", "start", "--no-block", "ft-to-kindle.service"])


# --- dispatch ---------------------------------------------------------------

def install() -> str:
    if config.IS_MAC:
        return install_launchd()
    if config.IS_LINUX and shutil.which("systemctl"):
        return install_systemd()
    raise RuntimeError("no supported scheduler on this OS (need launchd or systemd)")


def uninstall() -> str:
    return uninstall_launchd() if config.IS_MAC else uninstall_systemd()


def status() -> str:
    if config.IS_MAC:
        return status_launchd()
    if shutil.which("systemctl"):
        return status_systemd()
    return "no scheduler available"


def kick() -> None:
    kick_launchd() if config.IS_MAC else kick_systemd()
